naver:
  url:
    base: https://nid.naver.com/oauth2.0/
    redirect: http://localhost:8080/login/naver/callback
    userdata: https://openapi.naver.com/v1/nid/me

  client:
    id: shLrTHnjRILnVJD5mN2V
    secret: xS5mKrEnrv

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stay
    username: root
    password: db
    driver-class-name: com.mysql.cj.jdbc.Driver
